
spring:
  datasource:
    name: test  #数据库名
    url: jdbc:mysql://localhost:3306/demo_dev #url
    username: demo_dev #用户名
    password: demo_dev  #密码
    driver-class-name: com.mysql.jdbc.Driver  #数据库链接驱动
  #页面模板设置
  thymeleaf:
    cache: false

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.example.sys.entity
  global-config:
      id-type: 0
shiro:
  HashAlgorithmName: MD5
  HashIterations: 1024
  StoredCredentialsHexEncoded: true


